@echo off
chcp 65001

echo ALLUSERSPROFILE:  %ALLUSERSPROFILE%
echo CMDCMDLINE:  %CMDCMDLINE%
echo COMMONPROGRAMFILES:  %COMMONPROGRAMFILES%
echo COMPUTERNAME:  %COMPUTERNAME%
echo DATE:  %DATE%
echo HOMEDRIVE:  %HOMEDRIVE%
echo HOMESHARE:  %HOMESHARE%
echo NUMBER_OF_PROCESSORS:  %NUMBER_OF_PROCESSORS%
echo PATH:  %PATH%
echo PROCESSOR_ARCHITECTURE:  %PROCESSOR_ARCHITECTURE%
echo PROCESSOR_LEVEL:  %PROCESSOR_LEVEL%
echo PROGRAMDATA:  %PROGRAMDATA%
echo PROGRAMFILES(x86):  %PROGRAMFILES(x86)%
echo RANDOM:  %RANDOM%
echo SESSIONNAME:  %SESSIONNAME%
echo TIME:  %TIME%
echo USERNAME:  %USERNAME%
echo WINDIR:  %WINDIR%


echo COMSPEC: %COMSPEC%
echo ERRORLEVEL: %ERRORLEVEL%
echo HOMEPATH: %HOMEPATH%
echo LOCALAPPDATA: %LOCALAPPDATA%
echo LOGONSERVER: %LOGONSERVER%
echo OS: %OS%
echo PATHEXT: %PATHEXT%
echo PROCESSOR_IDENTIFIER: %PROCESSOR_IDENTIFIER%
echo PROCESSOR_REVISION: %PROCESSOR_REVISION%
echo PROGRAMFILES: %PROGRAMFILES%
echo PROMPT: %PROMPT%
echo SAFEBOOT_OPTION: %SAFEBOOT_OPTION%
echo SYSTEMDRIVE: %SYSTEMDRIVE%
echo TEMP: %TEMP%
echo TMP: %TMP%
echo USERDOMAIN: %USERDOMAIN%
echo USERPROFILE: %USERPROFILE%