//Задагние 6
ALTER SESSION SET CONTAINER = PNA_PDB
ALTER PLUGGABLE DATABASE ALL OPEN
//Задание 7 
CREATE TABLESPACE TS_PNAPDB
DATAFILE 'TS_PNAPDN.dbf'
SIZE 7M
AUTOEXTEND ON
NEXT 5M
MAXSIZE 20M;

CREATE TEMPORARY TABLESPACE TS_PNAPDB_TEMP
TEMPFILE 'TS_PNAPDB_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON
NEXT 3M
MAXSIZE 30M;

alter session set "_ORACLE_SCRIPT" = true;

//Профиль безопасности
CREATE PROFILE PF_PNA_PDB LIMIT
    FAILED_LOGIN_ATTEMPTS 3    
    PASSWORD_LOCK_TIME 1        
    PASSWORD_LIFE_TIME 90     
    PASSWORD_REUSE_TIME 365   
    PASSWORD_REUSE_MAX 10;  
    
//Пользователь 
CREATE USER U1_PNA_PDB
    IDENTIFIED BY 123 ---P111
    DEFAULT TABLESPACE TS_PNAPDB
    TEMPORARY TABLESPACE TS_PNAPDB_TEMP
    PROFILE PF_PNA_PDB
    ACCOUNT UNLOCK;
    
grant create session, create table, create view, drop any table, drop any view to U1_PNA_PDB  
GRANT UNLIMITED TABLESPACE TO U1_PNA_PDB;
